trigger:
  branches:
    include:
      - main

  paths:
    exclude:
      - pipe/*
      - Readme.md
      - .gitignore
      - GitVersion.yaml

pool:
  vmImage: ubuntu-latest

stages:
  - stage: VERSION_CONTROL
    jobs:
      - job: TAGGING
        steps:
          - template: ./version-control.yaml
            parameters:
              configPath: "./GitVersion.yaml"
  - stage: PUSH_TAG
    dependsOn: VERSION_CONTROL
    jobs:
      - job:
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              echo "Tagging $(Build.BuildNumber)"
              git tag $(Build.BuildNumber)
              git push origin $(Build.BuildNumber)
            workingDirectory: $(Build.SourcesDirectory)
            displayName: "Create and push tag"
