name: Terraform Tagging

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.tf'
  # pull_request:
  #   branches:
  #     - main
  #     - dev
  #   paths:
  #     - '**/*.tf'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semver:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      semver: ${{ steps.calc-semver.outputs.fullSemVer }}
      semverbeta: ${{ steps.calc-semver.outputs.majorMinorPatch }}-${{ steps.calc-semver.outputs.shortSha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.3.3
        with:
          versionSpec: '6.6.x'
          preferLatestVersion: true

      - name: Determine Version
        id: calc-semver
        uses: gittools/actions/gitversion/execute@v4.3.3
        with:
          configFilePath: GitVersion.yaml

  tag:
    runs-on: ubuntu-24.04
    needs:
      - semver
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create git tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ github.ref_name == 'main' && needs.semver.outputs.semver || needs.semver.outputs.semverbeta }}
          message: Terraform release
          tag_exists_error: false